"""
RankSmart — Multi-Agent SEO Audit Team
"""

import os, re, textwrap
from google.adk import ADKAgent, tool, state

# === Shared Firecrawl + Google CSE tools ===

@tool
def firecrawl_scrape(url: str) -> str:
    """Scrape the given URL using Firecrawl MCP and return Markdown content."""
    import requests
    fc_key = os.getenv("FIRECRAWL_API_KEY")
    headers = {"Authorization": f"Bearer {fc_key}", "Content-Type": "application/json"}
    data = {
        "url": url,
        "timeout": 180000,
        "maxDepth": 0,
        "formats": ["markdown"],
        "userAgent": "RankSmart/1.0"
    }
    r = requests.post("https://api.firecrawl.dev/scrape", headers=headers, json=data, timeout=180)
    r.raise_for_status()
    return r.text


@tool
def perform_google_search(query: str, limit: int = 10) -> str:
    """Perform a Google CSE search and return simplified JSON result list."""
    import requests
    api_key = os.getenv("GOOGLE_SEARCH_API_KEY")
    cse_id = os.getenv("GOOGLE_CSE_ID")
    url = f"https://www.googleapis.com/customsearch/v1?q={query}&key={api_key}&cx={cse_id}&num={limit}"
    r = requests.get(url, timeout=60)
    r.raise_for_status()
    return r.text


# === Core agents ===

class PageAuditorAgent(ADKAgent):
    """Collects data: scrape page + SERP."""
    async def run(self, s: state):
        target = s.input.strip()
        if not target.startswith("http"):
            target = re.search(r"https?://[^\s]+", s.input).group(0)
        s.page_markdown = await self.use(firecrawl_scrape, url=target)
        s.serp_json = await self.use(perform_google_search, query=target)
        return "Page content and SERP data collected."


class OptimizationAdvisorAgent(ADKAgent):
    """Creates the SEO audit report with Quick View summary."""
    async def run(self, s: state):
        from textwrap import dedent
        content = s.page_markdown[:10000]  # keep LLM input small
        report = dedent(f"""
        ## ⚡ Quick View Summary
        - URL: {s.input}
        - Keywords & Intent inferred from content
        - Core technical checks (noindex, meta tags, headings, links)
        - Content depth & keyword coverage
        - Competitor themes via SERP snapshot

        ## 🔍 Audit Narrative
        {content[:2000]}...
        """)
        s.audit_report = report
        return report


class ContentWriterAgent(ADKAgent):
    """Creates a ready-to-publish SEO-optimized article."""
    async def run(self, s: state):
        base = getattr(s, "audit_report", "")
        draft = f"# SEO Draft Article\n\n{base}\n\n(Generated by RankSmart)"
        s.draft_article = draft
        return draft


# === Router (message preprocessor) ===

def route_message(user_text: str) -> str:
    """If user sends just a URL, prepend 'Audit' automatically."""
    if re.match(r"^https?://", user_text.strip()):
        return f"Audit {user_text.strip()}"
    return user_text
